### ISSUE TITLE
Handle dates that are in the past

### ISSUE THREAD

**Issue by qroll** [cs2103jan2016-w09-4j/main#95]

**Comment by qroll** [comment]
Also for tasks where the end time is earlier than the start time

**Comment by sugarcontent** [comment]
http://stackoverflow.com/questions/24927701/how-to-compare-time-string-with-current-time-in-java

https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html#compareTo-java.time.LocalTime- Use compareTo()
